pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':FtcRobotController'
include ':TeamCode'
include ':offseason-teamcode'
project(':offseason-teamcode').projectDir = new File(rootProject.projectDir, 'libs/26-27_Offseason-Project/TeamCode')
